versionCheck: true

safety:
  fall: true
  lava: 60

#disabling:
#  levitation: false
#  changeWorld: false

# Vault required.
economy:
  enable: true
  async: false
  price: 500
  margin: 10 # If the refund amount is less than this, no refund will be given.
  # player, credit, time
  #cost: "500*(((player-1)/5)+1)"
  server: "" # Server account (Name or UUID, UUID is better.)
  refund: true # true/false/payer (Hint: 'payer' is refund to payer)

notice:
  enable:
    message: chat # false/chat/actionbar
    particle:
      type: VILLAGER_HAPPY # false/enum ( https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html )
      count: 10
      offset: { x:0.5, y:0.5, z:0.5 }
    sound:
      type: BLOCK_NOTE_BLOCK_CHIME # false/enum ( https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html )
      volume: 1.0
      pitch: 0.8
  disable:
    message: chat
    particle:
      type: SMOKE_LARGE
      count: 5
      offset: { x:0.5, y:0.5, z:0.5 }
    sound:
      type: BLOCK_NOTE_BLOCK_FLUTE
      volume: 1.0
      pitch: 0.5
  timeout:
    second: 30 # Warn before the end of flight. (Must be less than 60)
    message: chat
    particle:
      type: FIREWORKS_SPARK
      count: 10
      offset: { x:0.5, y:0.5, z:0.5 }
    sound:
      type: BLOCK_NOTE_BLOCK_PLING
      volume: 1.0
      pitch: 0.7
  payment:
    message: chat
    persist: actionbar # for persist flight payment.
    particle:
      type: BUBBLE_POP
      count: 1
      offset: { x:0, y:0, z:0 }
    sound:
      type: BLOCK_NOTE_BLOCK_BELL
      volume: 1.0
      pitch: 1.0
# payment.persist
# timeout.before

# Multi locale support.
locale:
  enable: true
  default: "en_us"


# Don't touch!
version: 2
