main: "jp.jyn.ebifly.PluginMain"
name: "EbiFly"
version: "${project.version}"
website: "${project.url}"
author: "HimaJyun( https://jyn.jp/ )"
description: "${project.description}"
softdepend: [ "Vault" ]
api-version: "1.17"

commands:
  fly:
    description: "\"/fly [time] [player]\" - I can fly!"
    aliases: [ "ebifly" ]

permissions:
  ebifly.fly: # 自分から飛べるか
    default: true
  ebifly.other: # 他人に施せるか
    default: true
  ebifly.receive: # TODO: 他人から受け取れるか
    default: true
  ebifly.free:
    default: op
  ebifly.version:
    default: op
  ebifly.reload:
    default: op
