main: "jp.jyn.ebifly.PluginMain"
name: "Fly"
version: "${project.version}"
website: "${project.url}"
author: "HimaJyun( https://jyn.jp/ )"
description: "${project.description}"
softdepend: [ "Vault", "PlaceholderAPI" ]
api-version: "1.17"

commands:
  fly:
    description: "\"/fly [time] [player]\" - I can fly!"
    aliases: [ "ebifly" ]

permissions:
  fly.fly.self:
    default: true
  fly.fly.other:
    default: true
  fly.restrict.respawn:
    default: true
  fly.restrict.world:
    default: true
  fly.restrict.gamemode:
    default: false
  fly.restrict.levitation:
    default: op
  fly.restrict.water:
    default: op
  fly.free:
    default: op
  fly.version:
    default: op
  fly.reload:
    default: op
  fly.fly.*:
    default: false
    children:
      fly.fly.self: true
      fly.fly.other: true
  fly.restrict.*:
    default: false
    children:
      fly.restrict.respawn: true
      fly.restrict.world: true
      fly.restrict.gamemode: true
      fly.restrict.levitation: true
      fly.restrict.water: true
  fly.op:
    default: false
    children:
      fly.free: true
      fly.version: true
      fly.reload: true
      fly.restrict.water: true
      fly.restrict.levitation: true
  fly.user:
    default: false
    children:
      fly.fly.self: true
      fly.fly.other: true
      fly.restrict.respawn: true
      fly.restrict.world: true
      #fly.restrict.gamemode: true
  fly.*:
    default: false
    children:
      fly.fly.self: true
      fly.fly.other: true
      fly.restrict.respawn: true
      fly.restrict.world: true
      fly.restrict.gamemode: true
      fly.restrict.water: true
      fly.restrict.levitation: true
      fly.free: true
      fly.version: true
      fly.reload: true
